### PR TITLE
Kp itinerary save concerts

### PR DESCRIPTION
**Pull request by keithrpotempa**
Itinerary Saving buttons for concerts are working mostly as desired. The last step is to remove the save button when appending to the Itinerary container. 

1. `git fetch --all`
2. `git checkout kp-itinerary-save-concerts`
3. Confirm that the following behavior is working:
- Search for a concert produces desired results
- Clicking on the Save button for a single result outputs it to the itinerary section

### CODE REVIEW

**Comment by MReeds** [comment]
Only the last listing has a functioning save button
also there is still a favorite restaurant header with the itinerary

**Comment by keithrpotempa** [comment]
I'm not sure exactly what was causing the issue, but taking a different approach resolved it. 
Rather than trying to add the event listener at the end of the foreach looping over the results, I waited until they results were all rendered, and then did a querySelectorAll to select all the buttons by class, then looped over them to add the event listener.

This appears to be working as desired. Please confirm at your earliest convenience.

**Comment by MReeds** [comment]
Saves to itinerary and now says favorite concert. Great job!

**Comment by sncandiani** [comment]
Grrrreat

**Comment by keithrpotempa** [comment]
Thanks, y'all! Merging away.

**Pull request merged**
