### PR TITLE
Kp parks api

### PR DESCRIPTION
**Pull request by keithrpotempa**
The parks API Manager 'alpha' is finished. Please review with the following steps:

1. `git fetch --all`
2. `git checkout kp-parks-api`
3. uncomment the last few lines:
`// const parksSearchResultPromise = parksApiManager.searchParks(parkSearchCriteria);

// parksSearchResultPromise.then(searchResults => {
//     console.log(searchResults);
// }); `
4. Confirm that the console of index.html contains some parks JSON information. 
5. Feel free to test its 'query' functionality further by changing the `parkSearchCriteria` const near the top

### CODE REVIEW

**Comment by MReeds** [comment]
Works as expected!

**Comment by sncandiani** [comment]
Just needs changes to the baseUrl so it isn't the same as restaurant

**Comment by ghost** [comment]
Looks good!

**Comment by sncandiani** [comment]
yes good

**Pull request merged**
