### PR TITLE
Added Restaurant Api

### PR DESCRIPTION
**Pull request by ghost**
1. Git fetch --all

2. Git checkout RN_Restaurant 

3. Uncomment these lines
  //  searchResultPromise.then(searchResults => {
 // console.log(searchResults);
 // });

4. Check that results generate an object in the "Console" 

5. (NEW) Check to see that Restaurant label is correctly tagged

### CODE REVIEW

**Comment by keithrpotempa** [comment]
I had a thought of a small change to make before we merge it. 

We have to change references of the following to be unique for each of our four API manager apps (eg. by adding the word 'restaurant' to them): 
- 'apiManager' 
- 'searchCriteria' 
- 'searchResultsPromise'

**Comment by MReeds** [comment]
Works as it should! Great job.

**Comment by keithrpotempa** [comment]
👍 Pending these last changes:
- change `searchResultPromise` to `searchResultPromiseRestaurant`
- comment out the line of `const searchResultPromiseRestaurant =`

**Comment by sncandiani** [comment]
Yep, looks like it works!

**Pull request merged**
